Enhance the dashboard UI with widgets to match the designs
gtiosclub/Vineyard pull request #58
Opened 2024-10-24 23:38 UTC by hiimjin

# Pull Request Title
Enhance the dashboard UI with widgets to match the designs

## Description
Enhance the dashboard UI with widgets to match the designs

What does this PR fix? You can mention the issue number like
so to reference the issue automatically: "Fixes #44 "

## Screenshot/Recording (if applicable)
<img width="293" alt="Screenshot 2024-10-24 at 7 38 14 PM" src="https://github.com/user-attachments/assets/4c05318c-b0b6-4061-a092-1bcc858d7e7f">

2024-10-29 23:03 UTC, sankaet8 requested changes, later dismissed
please make the changes requested, great work!!

2024-10-29 23:03 UTC, sankaet8 commented on Vineyard/Vineyard/Widget.swift
> +import SwiftUICore
we do not need swiftui core, only swiftUI

2024-10-29 23:03 UTC, sankaet8 commented on Vineyard/Vineyard/Widget.swift
> +//struct TodaysTasksWidgetFull: Widget {
Please remove these comments

2024-10-29 23:03 UTC, sankaet8 commented on Vineyard/Vineyard/Widget.swift
> +//struct RecentActivitiesWidgetFull: Widget {
Please remove these comments as well

2024-10-29 23:03 UTC, sankaet8 commented on Vineyard/Vineyard/Widget.swift
Would be nice to split this up into several files each with one type of widget for easier file organization

2024-11-05 04:41 UTC, rahulon12 requested changes
Can you try using `Grid` instead of multiple `VStack`s and `HStack`s? It has built-in support for col span, etc.

https://developer.apple.com/documentation/swiftui/grid

2024-11-07 03:56 UTC, rahulon12 approved these changes
Looks good for now. We will need to change the widget implementation to make it more flexible for data flow, etc.

2024-11-07 04:04 UTC, merged